### ISSUE TITLE
Please help me to debug "make load" failed,thanks.

### ISSUE THREAD

**Issue by ccccbjcn** [hirishh/ledger-toolchain#1]
Hi @hirishh  
I setup the toolchain and sdk, run "make load" for leger-nuls, but I got the below failed return. 
Could you help me to debug the root cause? What did I miss?

```
root@ubuntu:/home/cbj/NULS/ledger-nuls# make load
TARGET_NAME=TARGET_BLUE TARGET_ID=0x31000004
BOLOS_ENV=/home/cbj/NULS/ledger-toolchain/bolos_env
APPNAME="Nuls"
BOLOS_ENV=/home/cbj/NULS/ledger-toolchain/bolos_env
python -m ledgerblue.loadApp --appFlags 0x40 --targetVersion "" --curve secp256k1 --tlv --targetId 0x31000004 --delete --fileName bin/app.hex --appName "Nuls" --appVersion 0.1.0 --dataSize `cat debug/app.map |grep _nvram_data_size | tr -s ' ' | cut -f2 -d' '` `ICONHEX=\`python /home/cbj/NULS/ledger-toolchain/blue-secure-sdk/icon.py badge_menu.gif hexbitmaponly 2>/dev/null\` ; [ ! -z "$ICONHEX" ] && echo "--icon $ICONHEX"`  --path "44'/8964'" --path "44'/261'"
Generated random root public key : 040f6ba1db16226596b79f8bcb6ee27ec80f4ea8dea57f3bf14892a07a03346e5fec2847cd902b769cd8da09727794454951fec1505afb2e540a7e3f0fcc213632
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ledgerblue/loadApp.py", line 202, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/usr/local/lib/python2.7/dist-packages/ledgerblue/deployed.py", line 91, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/usr/local/lib/python2.7/dist-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6484 (Are you using the correct targetId?)
Makefile:107: recipe for target 'load' failed
make: *** [load] Error 1

```

**Comment by hirishh** [comment]
Some questions:
 - What ledger device are you using? Which Firmware version?
 - Did you checkout the correct sdk version?

I see `python /home/cbj/NULS/ledger-toolchain/blue-secure-sdk/` why blue sdk?

Maybe something changed. Here more info: https://ledger.readthedocs.io/en/latest/userspace/getting_started.html

**Comment by ccccbjcn** [comment]
Hi  @hirishh 
My ledger device is Nano X, so I use blue sdk(changed configure.env).
It firmware version info:Secure Element  1.2.4-1, Microcontroller 2.8.
Per setup-installenv.sh, it did not checkout blue sdk with version.
What is your suggestion?
I will readout wiki as https://ledger.readthedocs.io/en/latest/userspace/getting_started.html.
```
if [ ! -d blue-secure-sdk ]; then
  git clone https://github.com/LedgerHQ/blue-secure-sdk
fi
```

I change sdk to nanos-secure-sdk, and exec "make load" getting below errors:
```
root@ubuntu:/home/cbj/NULS/ledger-nuls# make load
TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100004 TARGET_VERSION=1.6.0
BOLOS_ENV=/home/cbj/NULS/ledger-toolchain/bolos_env
APPNAME="Nuls"
BOLOS_ENV=/home/cbj/NULS/ledger-toolchain/bolos_env
[GLYPH] Compiling...
Prepare directories
[DEP]  dep/ux_stack.d
In file included from /home/cbj/NULS/ledger-toolchain/nanos-secure-sdk/lib_ux/src/ux_stack.c:19:
/home/cbj/NULS/ledger-toolchain/nanos-secure-sdk/lib_ux/include/ux.h:27:4: warning: Enable legacy UX definition [-W#warnings]
  #warning Enable legacy UX definition
   ^
In file included from /home/cbj/NULS/ledger-toolchain/nanos-secure-sdk/lib_ux/src/ux_stack.c:19:
In file included from /home/cbj/NULS/ledger-toolchain/nanos-secure-sdk/lib_ux/include/ux.h:209:
In file included from /home/cbj/NULS/ledger-toolchain/nanos-secure-sdk/include/os_io_seproxyhal.h:151:
/home/cbj/NULS/ledger-toolchain/nanos-secure-sdk/lib_u2f/include/u2f_service.h:20:10: fatal error: 'string.h' file not found
#include <string.h>
         ^~~~~~~~~~
1 warning and 1 error generated.
```
